version: '3.9'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'app'
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8000
